apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: ClusterIP  # Internal exposure only
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # Port inside the cluster
      targetPort: 8080 # Port the app listens on inside the pod
